---
title: "data_preprocessing_bias"
author: "Drew Walker"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
```

```{r, data_load}
broad_patients <- read_csv("SC_NOTES_PATIENTS_BROAD.csv")
broad_patients <- broad_patients %>% 
  mutate(dataset = "broad")
crisis_patients <- read_csv("SC_NOTES_PATIENTS_CRISIS.csv")
crisis_patients <- crisis_patients %>% 
  mutate(dataset = "crisis")

#full broad and crisis patient cohorts 
full_df <- bind_rows(broad_patients,crisis_patients)
```
# Text preprocessing
```{r, text_preprocessing}
full_df_sentences <- full_df %>%
  unnest_sentences(sentence,TEXT,to_lower = FALSE)

full_df_sentences$sentence <- gsub("[\r\n]","",full_df_sentences$sentence)

full_df_sentences_clean <- full_df_sentences%>% filter(nchar(sentence)>15) %>% 
  mutate(questioning_credibility="",
         questioning_credibility_quote="",
         disapproval="",
         disapproval_quote="",
         stereotyping="",
         stereotyping_quote="",
         difficult_patient="",
         difficult_patient_quote="",
         unilateral_decisions="",
         unilateral_decisions_quote="",
         compliment="",
         compliment_quote="",
         approval="",
         approval_quote="",
         self_disclosure="",
         self_disclosure_quote="",
         minimize_blame="",
         minimize_blame_quote="",
         personalize="",
         personalize_quote="",
         bilateral_decision="",
         bilateral_decision_quote="",
         notes_or_concerns="")
write_csv(full_df_sentences_clean,"full_df_sentences_clean.csv")
# This actually filters out more than the python code, likely an issue with slightly different regex 
```

